APP_NAME = 'DSPDemo'
APP_VERSION = '0.0.1'
APP_COPYRIGHT = 'Olivier Bélanger, 2018'

AUDIO_NCHNLS = 2
AUDIO_BUFSIZE = 512
AUDIO_DUPLEX = 0

MODULE_DOC_ID = 99
MODULE_FIRST_ID = 100

APP_BACKGROUND_COLOUR = "#CCCCD0"
USR_PANEL_BACK_COLOUR = "#DDDDE0"
HEADTITLE_BACK_COLOUR = "#9999A0"
