APP_NAME = 'DSPDemo'
APP_VERSION = '0.0.1'
APP_COPYRIGHT = 'Olivier Bélanger, 2018'

AUDIO_NCHNLS = 2

MODULE_DOC_ID = 99
MODULE_FIRST_ID = 100

APP_BACKGROUND_COLOUR = "#BBBBCC"
USR_PANEL_BACK_COLOUR = "#CCCCDD"
HEADTITLE_BACK_COLOUR = "#9999AA"
